export default [
  // {
  //   id: 'home',
  //   icon: 'home',
  //   label: '首页',
  //   parentId: '0',
  //   moduleCode: 'home',
  //   moduleUrl: 'home',
  // },
  // {
  //   id: 'LocalLaw',
  //   icon: 'icon-difafawu',
  //   label: '地方行政法规',
  //   parentId: '0',
  //   moduleCode: 'LocalLaw',
  //   moduleUrl: 'LocalLaw',
  // },
  {
    id: 'WaterDataQuery',
    icon: 'icon-shuizhizhuodu',
    label: '数据查询',
    parentId: '0',
    moduleCode: 'WaterDataQuery',
    moduleUrl: 'WaterDataQuery',
  },
  {
    id: 'WaterAlarmManage',
    icon: 'icon-changyongtubiao',
    label: '报警管理',
    parentId: '0',
    moduleCode: 'WaterAlarmManage',
    moduleUrl: 'WaterAlarmManage',
  },
  {
    id: 'MonitorCenter',
    icon: 'icon-jianguan',
    label: '监管中心',
    parentId: '0',
    moduleCode: 'MonitorCenter',
    moduleUrl: 'MonitorCenter',
    children: [
      {
        id: 'RankDetail',
        icon: 'icon-rankdetail',
        label: '运维监管排名明细',
        parentId: '0',
        moduleCode: 'RankDetail',
        moduleUrl: 'RankDetail',
      },
      {
        id: 'ItemRegister',
        icon: 'icon-register',
        label: '事项登记',
        parentId: '0',
        moduleCode: 'ItemRegister',
        moduleUrl: 'ItemRegister',
      },
    ],
  },
  {
    id: 'SchemeConfig',
    icon: 'icon-schemeconfig',
    label: '方案配置',
    parentId: '0',
    moduleCode: 'SchemeConfig',
    moduleUrl: 'SchemeConfig',
    children: [
      {
        id: 'AutoScoreConfig',
        icon: 'icon-autoconfig',
        label: '自动积分方案配置',
        parentId: '0',
        moduleCode: 'AutoScoreConfig',
        moduleUrl: 'AutoScoreConfig',
      },
      {
        id: 'ManualScoreConfig',
        icon: 'icon-manualconfig',
        label: '手动积分方案配置',
        parentId: '0',
        moduleCode: 'ManualScoreConfig',
        moduleUrl: 'ManualScoreConfig',
      },
      {
        id: 'ScoreCycleConfig',
        icon: 'icon-cycleconfig',
        label: '计分周期配置',
        parentId: '0',
        moduleCode: 'ScoreCycleConfig',
        moduleUrl: 'ScoreCycleConfig',
      },
    ],
  },
  {
    id: 'Notice',
    icon: 'icon-notice',
    label: '通知公告',
    parentId: '0',
    moduleCode: 'Notice',
    moduleUrl: 'Notice',
  },
  {
    id: 'EnterManagement',
    icon: 'icon-building',
    label: '企业管理',
    parentId: '0',
    moduleCode: 'EnterManagement',
    moduleUrl: 'EnterManagement',
  },
  {
    id: 'UserManagement',
    icon: 'icon-users',
    label: '用户管理',
    parentId: '0',
    moduleCode: 'UserManagement',
    moduleUrl: 'UserManagement',
  },
  {
    id: 'RoleManagement',
    icon: 'icon-role',
    label: '角色管理',
    parentId: '0',
    moduleCode: 'RoleManagement',
    moduleUrl: 'RoleManagement',
  },
  {
    id: 'EnterDeclare',
    icon: 'icon-declare',
    label: '企业申报',
    parentId: '0',
    moduleCode: 'EnterDeclare',
    moduleUrl: 'EnterDeclare',
  },
  {
    id: 'FaultAlarmQuery',
    icon: 'icon-faultalarm',
    label: '故障报警查询',
    parentId: '0',
    moduleCode: 'FaultAlarmQuery',
    moduleUrl: 'FaultAlarmQuery',
  },
  {
    id: 'RealStandManage',
    icon: 'icon-realstand',
    label: '真实超标管理',
    parentId: '0',
    moduleCode: 'RealStandManage',
    moduleUrl: 'RealStandManage',
  },
  {
    id: 'ExcessNotice',
    icon: 'icon-excessnotice',
    label: '超标通告单',
    parentId: '0',
    moduleCode: 'ExcessNotice',
    moduleUrl: 'ExcessNotice',
  },
  {
    id: 'OperatRecords',
    icon: 'icon-operaterecord',
    label: '运维记录',
    parentId: '0',
    moduleCode: 'OperatRecords',
    moduleUrl: 'OperatRecords',
  },
  // {
  //   id: 'Test',
  //   icon: 'icon-frame',
  //   label: '样式修改测试',
  //   parentId: '0',
  //   moduleCode: 'Test',
  //   moduleUrl: 'Test',
  // },
  {
    id: 'MaintainCompany',
    icon: 'icon-schemeconfig',
    label: '运维单位',
    parentId: '0',
    moduleCode: 'MaintainCompany',
    moduleUrl: 'MaintainCompany',
    children: [
      {
        id: 'MaintainAutoScoreConfig',
        icon: 'icon-autoconfig',
        label: '自动计分方案配置',
        parentId: '0',
        moduleCode: 'MaintainAutoScoreConfig',
        moduleUrl: 'MaintainAutoScoreConfig',
      },
      {
        id: 'MaintainManualScoreConfig',
        icon: 'icon-manualconfig',
        label: '手动计分方案配置',
        parentId: '0',
        moduleCode: 'MaintainManualScoreConfig',
        moduleUrl: 'MaintainManualScoreConfig',
      },
      {
        id: 'MaintainScoreCycleConfig',
        icon: 'icon-cycleconfig',
        label: '计分周期配置',
        parentId: '0',
        moduleCode: 'MaintainScoreCycleConfig',
        moduleUrl: 'MaintainScoreCycleConfig',
      },
      {
        id: 'MaintainRankDetail',
        icon: 'icon-rankdetail',
        label: '排名明细',
        parentId: '0',
        moduleCode: 'MaintainRankDetail',
        moduleUrl: 'MaintainRankDetail',
      },
      {
        id: 'MaintainItemRegister',
        icon: 'icon-register',
        label: '重大事项登记',
        parentId: '0',
        moduleCode: 'MaintainItemRegister',
        moduleUrl: 'MaintainItemRegister',
      },
      {
        id: 'MaintainManagement',
        icon: 'icon-building',
        label: '运维单位管理',
        parentId: '0',
        moduleCode: 'MaintainManagement',
        moduleUrl: 'MaintainManagement',
      },
    ],
  },
];
